In [1]:
import pandas as pd
import numpy as np
import wrangle

### 1. Acquire data from mySQL using the python module to connect and query. You will want to end with a single dataframe. Make sure to include: the logerror, all fields related to the properties that are available. You will end up using all the tables in the database.

In [2]:
# Acquiring the data using the wrangle
zillow_sql_query = wrangle.get_zillow_data()
# I am working with a copy of the SQL query to be able to access it faster
df = zillow_sql_query.copy()

In [3]:
zillow_sql_query.shape, df.shape

((52439, 68), (52439, 68))

In [4]:
df.head()

,typeconstructiontypeid,storytypeid,propertylandusetypeid,parcelid,heatingorsystemtypeid,buildingclasstypeid,architecturalstyletypeid,airconditioningtypeid,id,basementsqft,...,censustractandblock,airconditioningdesc,architecturalstyledesc,buildingclassdesc,heatingorsystemdesc,logerror,maxdate,propertylandusedesc,storydesc,typeconstructiondesc
0,NaN,NaN,261.0,14297519,NaN,NaN,NaN,NaN,1727539,NaN,...,6.059063e+13,NaN,NaN,NaN,NaN,0.025595,2017-01-01,Single Family Residential,NaN,NaN
1,NaN,NaN,261.0,17052889,NaN,NaN,NaN,NaN,1387261,NaN,...,6.111001e+13,NaN,NaN,NaN,NaN,0.055619,2017-01-01,Single Family Residential,NaN,NaN
2,NaN,NaN,261.0,14186244,NaN,NaN,NaN,NaN,11677,NaN,...,6.059022e+13,NaN,NaN,NaN,NaN,0.005383,2017-01-01,Single Family Residential,NaN,NaN
3,NaN,NaN,261.0,12177905,2.0,NaN,NaN,NaN,2288172,NaN,...,6.037300e+13,NaN,NaN,NaN,Central,-0.103410,2017-01-01,Single Family Residential,NaN,NaN
4,NaN,NaN,261.0,12095076,2.0,NaN,NaN,1.0,781532,NaN,...,6.037461e+13,Central,NaN,NaN,Central,-0.001011,2017-01-01,Single Family Residential,NaN,NaN

### Summarize your data (summary stats, info, dtypes, shape, distributions, value_counts, etc.)

In [5]:
df.shape

(52439, 68)

In [6]:
df.dtypes

typeconstructiontypeid          float64
storytypeid                     float64
propertylandusetypeid           float64
parcelid                          int64
heatingorsystemtypeid           float64
buildingclasstypeid             float64
architecturalstyletypeid        float64
airconditioningtypeid           float64
id                                int64
basementsqft                    float64
bathroomcnt                     float64
bedroomcnt                      float64
buildingqualitytypeid           float64
calculatedbathnbr               float64
decktypeid                      float64
finishedfloor1squarefeet        float64
calculatedfinishedsquarefeet    float64
finishedsquarefeet12            float64
finishedsquarefeet13            float64
finishedsquarefeet15            float64
finishedsquarefeet50            float64
finishedsquarefeet6             float64
fips                            float64
fireplacecnt                    float64
fullbathcnt                     float64
garagecarcnt                    float64
garagetotalsqft                 float64
hashottuborspa                  float64
latitude                        float64
longitude                       float64
lotsizesquarefeet               float64
poolcnt                         float64
poolsizesum                     float64
pooltypeid10                    float64
pooltypeid2                     float64
pooltypeid7                     float64
propertycountylandusecode        object
propertyzoningdesc               object
rawcensustractandblock          float64
regionidcity                    float64
regionidcounty                  float64
regionidneighborhood            float64
regionidzip                     float64
roomcnt                         float64
threequarterbathnbr             float64
unitcnt                         float64
yardbuildingsqft17              float64
yardbuildingsqft26              float64
yearbuilt                       float64
numberofstories                 float64
fireplaceflag                   float64
structuretaxvaluedollarcnt      float64
taxvaluedollarcnt               float64
assessmentyear                  float64
landtaxvaluedollarcnt           float64
taxamount                       float64
taxdelinquencyflag               object
taxdelinquencyyear              float64
censustractandblock             float64
airconditioningdesc              object
architecturalstyledesc           object
buildingclassdesc               float64
heatingorsystemdesc              object
logerror                        float64
maxdate                          object
propertylandusedesc              object
storydesc                        object
typeconstructiondesc             object
dtype: object

In [7]:
round(df.describe().T, 2)

,count,mean,std,min,25%,50%,75%,max
typeconstructiontypeid,76.0,5.970000e+00,2.300000e-01,4.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00
storytypeid,47.0,7.000000e+00,0.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
propertylandusetypeid,52439.0,2.610000e+02,0.000000e+00,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02
parcelid,52439.0,1.299618e+07,3.348015e+06,1.071186e+07,1.151021e+07,1.257748e+07,1.412945e+07,1.676878e+08
heatingorsystemtypeid,33935.0,3.970000e+00,2.560000e+00,1.000000e+00,2.000000e+00,2.000000e+00,7.000000e+00,2.400000e+01
buildingclasstypeid,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
architecturalstyletypeid,70.0,7.100000e+00,2.670000e+00,2.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,2.100000e+01
airconditioningtypeid,13638.0,2.440000e+00,3.850000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.300000e+01
id,52439.0,1.497229e+06,8.594303e+05,3.490000e+02,7.578615e+05,1.500783e+06,2.241440e+06,2.982270e+06
basementsqft,47.0,6.789800e+02,7.118300e+02,3.800000e+01,2.635000e+02,5.120000e+02,8.095000e+02,3.560000e+03
bathroomcnt,52439.0,2.300000e+00,1.020000e+00,0.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.800000e+01
bedroomcnt,52439.0,3.300000e+00,9.500000e-01,0.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,1.400000e+01
buildingqualitytypeid,33740.0,6.260000e+00,1.720000e+00,1.000000e+00,5.000000e+00,6.000000e+00,8.000000e+00,1.200000e+01
calculatedbathnbr,52302.0,2.300000e+00,1.020000e+00,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.800000e+01
decktypeid,389.0,6.600000e+01,0.000000e+00,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01
finishedfloor1squarefeet,4379.0,1.545740e+03,6.749800e+02,1.840000e+02,1.151000e+03,1.410000e+03,1.759500e+03,6.912000e+03
calculatedfinishedsquarefeet,52357.0,1.922890e+03,1.004380e+03,1.280000e+02,1.268000e+03,1.659000e+03,2.306000e+03,2.192900e+04
finishedsquarefeet12,52192.0,1.925050e+03,1.004290e+03,1.280000e+02,1.270000e+03,1.660500e+03,2.308000e+03,2.192900e+04
finishedsquarefeet13,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
finishedsquarefeet15,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
finishedsquarefeet50,4379.0,1.566510e+03,7.446600e+02,1.840000e+02,1.152000e+03,1.414000e+03,1.770500e+03,1.246700e+04
finishedsquarefeet6,165.0,1.241080e+03,7.769600e+02,3.800000e+02,7.840000e+02,1.008000e+03,1.320000e+03,5.598000e+03
fips,52439.0,6.049130e+03,2.103000e+01,6.037000e+03,6.037000e+03,6.037000e+03,6.059000e+03,6.111000e+03
fireplacecnt,7241.0,1.210000e+00,5.100000e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.000000e+00
fullbathcnt,52302.0,2.240000e+00,9.900000e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.800000e+01
garagecarcnt,18013.0,1.950000e+00,5.500000e-01,0.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,1.400000e+01
garagetotalsqft,18013.0,4.958800e+02,1.570500e+02,0.000000e+00,4.260000e+02,4.620000e+02,5.670000e+02,4.251000e+03
hashottuborspa,1515.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
latitude,52439.0,3.402253e+07,2.739808e+05,3.334062e+07,3.382690e+07,3.402376e+07,3.418715e+07,3.481877e+07
longitude,52439.0,-1.181942e+08,3.566252e+05,-1.194754e+08,-1.184007e+08,-1.181531e+08,-1.179292e+08,-1.175546e+08
lotsizesquarefeet,52070.0,1.133982e+04,8.674929e+04,2.360000e+02,5.583000e+03,6.840500e+03,8.798750e+03,6.971010e+06
poolcnt,11096.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
poolsizesum,867.0,5.183200e+02,1.564700e+02,2.400000e+01,4.245000e+02,5.000000e+02,6.000000e+02,1.500000e+03
pooltypeid10,444.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid2,1071.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid7,10009.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
rawcensustractandblock,52439.0,6.049441e+07,2.086585e+05,6.037101e+07,6.037401e+07,6.037620e+07,6.059042e+07,6.111009e+07
regionidcity,51402.0,3.350149e+04,4.917601e+04,3.491000e+03,1.244700e+04,2.481200e+04,4.022700e+04,3.965560e+05
regionidcounty,52439.0,2.524610e+03,8.040000e+02,1.286000e+03,1.286000e+03,3.101000e+03,3.101000e+03,3.101000e+03
regionidneighborhood,19033.0,1.802671e+05,1.598249e+05,6.952000e+03,4.113100e+04,1.182080e+05,2.745140e+05,7.641670e+05
regionidzip,52413.0,9.663583e+04,4.605190e+03,9.598200e+04,9.620600e+04,9.641200e+04,9.699500e+04,3.996750e+05
roomcnt,52439.0,1.890000e+00,3.150000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,1.500000e+01
threequarterbathnbr,6724.0,1.010000e+00,1.400000e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.000000e+00
unitcnt,33847.0,1.000000e+00,3.000000e-02,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00
yardbuildingsqft17,1937.0,3.376300e+02,2.500200e+02,1.100000e+01,2.000000e+02,2.800000e+02,4.000000e+02,3.191000e+03
yardbuildingsqft26,63.0,2.256200e+02,1.885100e+02,1.200000e+01,7.150000e+01,1.800000e+02,3.170000e+02,8.680000e+02
yearbuilt,52323.0,1.963390e+03,2.313000e+01,1.878000e+03,1.950000e+03,1.961000e+03,1.979000e+03,2.016000e+03
numberofstories,14559.0,1.410000e+00,5.400000e-01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,6.000000e+00
fireplaceflag,81.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
structuretaxvaluedollarcnt,52355.0,1.965373e+05,2.543440e+05,1.290000e+02,7.707250e+04,1.318110e+05,2.263345e+05,9.164901e+06
taxvaluedollarcnt,52438.0,5.296981e+05,7.519060e+05,1.000000e+03,1.937515e+05,3.736120e+05,6.193018e+05,4.906124e+07
assessmentyear,52439.0,2.016000e+03,0.000000e+00,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03
landtaxvaluedollarcnt,52438.0,3.334719e+05,5.705370e+05,1.610000e+02,7.602825e+04,2.180320e+05,4.086202e+05,4.895220e+07
taxamount,52435.0,6.453510e+03,8.755660e+03,4.918000e+01,2.656280e+03,4.647740e+03,7.377390e+03,5.866393e+05
taxdelinquencyyear,2079.0,1.410000e+01,2.390000e+00,4.000000e+00,1.400000e+01,1.500000e+01,1.500000e+01,9.900000e+01
censustractandblock,52316.0,6.050238e+13,1.859068e+12,6.037101e+13,6.037401e+13,6.037620e+13,6.059042e+13,4.830301e+14
buildingclassdesc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
logerror,52439.0,2.000000e-02,1.800000e-01,-4.660000e+00,-2.000000e-02,1.000000e-02,4.000000e-02,5.260000e+00

In [8]:
df.info

<bound method DataFrame.info of        typeconstructiontypeid  storytypeid  propertylandusetypeid  parcelid  \
0                         NaN          NaN                  261.0  14297519
1                         NaN          NaN                  261.0  17052889
2                         NaN          NaN                  261.0  14186244
3                         NaN          NaN                  261.0  12177905
4                         NaN          NaN                  261.0  12095076
...                       ...          ...                    ...       ...
52434                     NaN          NaN                  261.0  12412492
52435                     NaN          NaN                  261.0  11000655
52436                     NaN          NaN                  261.0  17239384
52437                     NaN          NaN                  261.0  12773139
52438                     NaN          NaN                  261.0  12826780

       heatingorsystemtypeid  buildingclasstypeid  architecturalstyletypeid  \
0                        NaN                  NaN                       NaN
1                        NaN                  NaN                       NaN
2                        NaN                  NaN                       NaN
3                        2.0                  NaN                       NaN
4                        2.0                  NaN                       NaN
...                      ...                  ...                       ...
52434                    2.0                  NaN                       NaN
52435                    2.0                  NaN                       NaN
52436                    NaN                  NaN                       NaN
52437                    2.0                  NaN                       NaN
52438                    2.0                  NaN                       NaN

       airconditioningtypeid       id  basementsqft  ...  censustractandblock  \
0                        NaN  1727539           NaN  ...         6.059063e+13
1                        NaN  1387261           NaN  ...         6.111001e+13
2                        NaN    11677           NaN  ...         6.059022e+13
3                        NaN  2288172           NaN  ...         6.037300e+13
4                        1.0   781532           NaN  ...         6.037461e+13
...                      ...      ...           ...  ...                  ...
52434                    NaN  2274245           NaN  ...         6.037555e+13
52435                    NaN   673515           NaN  ...         6.037101e+13
52436                    NaN  2968375           NaN  ...         6.111008e+13
52437                    1.0  1843709           NaN  ...         6.037434e+13
52438                    NaN  1187175           NaN  ...         6.037503e+13

       airconditioningdesc  architecturalstyledesc  buildingclassdesc  \
0                      NaN                     NaN                NaN
1                      NaN                     NaN                NaN
2                      NaN                     NaN                NaN
3                      NaN                     NaN                NaN
4                  Central                     NaN                NaN
...                    ...                     ...                ...
52434                  NaN                     NaN                NaN
52435                  NaN                     NaN                NaN
52436                  NaN                     NaN                NaN
52437              Central                     NaN                NaN
52438                  NaN                     NaN                NaN

       heatingorsystemdesc  logerror     maxdate        propertylandusedesc  \
0                      NaN  0.025595  2017-01-01  Single Family Residential
1                      NaN  0.055619  2017-01-01  Single Family Residential
2                      NaN  0.005383  2017-01-01  Single Family Residential
3                  Central -0.103410  2017-01-01  Single Family Residential
4                  Central -0.001011  2017-01-01  Single Family Residential
...                    ...       ...         ...                        ...
52434              Central  0.001082  2017-09-19  Single Family Residential
52435              Central  0.020615  2017-09-20  Single Family Residential
52436                  NaN  0.013209  2017-09-21  Single Family Residential
52437              Central  0.037129  2017-09-21  Single Family Residential
52438              Central  0.007204  2017-09-25  Single Family Residential

       storydesc  typeconstructiondesc
0            NaN                   NaN
1            NaN                   NaN
2            NaN                   NaN
3            NaN                   NaN
4            NaN                   NaN
...          ...                   ...
52434        NaN                   NaN
52435        NaN                   NaN
52436        NaN                   NaN
52437        NaN                   NaN
52438        NaN                   NaN

[52439 rows x 68 columns]>

In [9]:
# what percentage of null values for every column.  weird that all my buildingclasstypeid
# are null after sql query, there were values before

df.isnull().sum()/len(df)*100

typeconstructiontypeid           99.855070
storytypeid                      99.910372
propertylandusetypeid             0.000000
parcelid                          0.000000
heatingorsystemtypeid            35.286714
buildingclasstypeid             100.000000
architecturalstyletypeid         99.866512
airconditioningtypeid            73.992639
id                                0.000000
basementsqft                     99.910372
bathroomcnt                       0.000000
bedroomcnt                        0.000000
buildingqualitytypeid            35.658575
calculatedbathnbr                 0.261256
decktypeid                       99.258186
finishedfloor1squarefeet         91.649345
calculatedfinishedsquarefeet      0.156372
finishedsquarefeet12              0.471023
finishedsquarefeet13            100.000000
finishedsquarefeet15            100.000000
finishedsquarefeet50             91.649345
finishedsquarefeet6              99.685349
fips                              0.000000
fireplacecnt                     86.191575
fullbathcnt                       0.261256
garagecarcnt                     65.649612
garagetotalsqft                  65.649612
hashottuborspa                   97.110929
latitude                          0.000000
longitude                         0.000000
lotsizesquarefeet                 0.703675
poolcnt                          78.840176
poolsizesum                      98.346650
pooltypeid10                     99.153302
pooltypeid2                      97.957627
pooltypeid7                      80.913061
propertycountylandusecode         0.000000
propertyzoningdesc               35.452621
rawcensustractandblock            0.000000
regionidcity                      1.977536
regionidcounty                    0.000000
regionidneighborhood             63.704495
regionidzip                       0.049581
roomcnt                           0.000000
threequarterbathnbr              87.177482
unitcnt                          35.454528
yardbuildingsqft17               96.306184
yardbuildingsqft26               99.879860
yearbuilt                         0.221209
numberofstories                  72.236313
fireplaceflag                    99.845535
structuretaxvaluedollarcnt        0.160186
taxvaluedollarcnt                 0.001907
assessmentyear                    0.000000
landtaxvaluedollarcnt             0.001907
taxamount                         0.007628
taxdelinquencyflag               96.035394
taxdelinquencyyear               96.035394
censustractandblock               0.234558
airconditioningdesc              73.992639
architecturalstyledesc           99.866512
buildingclassdesc               100.000000
heatingorsystemdesc              35.286714
logerror                          0.000000
maxdate                           0.000000
propertylandusedesc               0.000000
storydesc                        99.910372
typeconstructiondesc             99.855070
dtype: float64

In [10]:
df.isnull().sum()

typeconstructiontypeid          52363
storytypeid                     52392
propertylandusetypeid               0
parcelid                            0
heatingorsystemtypeid           18504
buildingclasstypeid             52439
architecturalstyletypeid        52369
airconditioningtypeid           38801
id                                  0
basementsqft                    52392
bathroomcnt                         0
bedroomcnt                          0
buildingqualitytypeid           18699
calculatedbathnbr                 137
decktypeid                      52050
finishedfloor1squarefeet        48060
calculatedfinishedsquarefeet       82
finishedsquarefeet12              247
finishedsquarefeet13            52439
finishedsquarefeet15            52439
finishedsquarefeet50            48060
finishedsquarefeet6             52274
fips                                0
fireplacecnt                    45198
fullbathcnt                       137
garagecarcnt                    34426
garagetotalsqft                 34426
hashottuborspa                  50924
latitude                            0
longitude                           0
lotsizesquarefeet                 369
poolcnt                         41343
poolsizesum                     51572
pooltypeid10                    51995
pooltypeid2                     51368
pooltypeid7                     42430
propertycountylandusecode           0
propertyzoningdesc              18591
rawcensustractandblock              0
regionidcity                     1037
regionidcounty                      0
regionidneighborhood            33406
regionidzip                        26
roomcnt                             0
threequarterbathnbr             45715
unitcnt                         18592
yardbuildingsqft17              50502
yardbuildingsqft26              52376
yearbuilt                         116
numberofstories                 37880
fireplaceflag                   52358
structuretaxvaluedollarcnt         84
taxvaluedollarcnt                   1
assessmentyear                      0
landtaxvaluedollarcnt               1
taxamount                           4
taxdelinquencyflag              50360
taxdelinquencyyear              50360
censustractandblock               123
airconditioningdesc             38801
architecturalstyledesc          52369
buildingclassdesc               52439
heatingorsystemdesc             18504
logerror                            0
maxdate                             0
propertylandusedesc                 0
storydesc                       52392
typeconstructiondesc            52363
dtype: int64

In [11]:
df.parcelid.value_counts()

11991059    3
12941764    2
12478591    2
11460921    2
10984661    2
           ..
17297000    1
11388525    1
11394670    1
12154589    1
12853244    1
Name: parcelid, Length: 52320, dtype: int64

In [12]:
df.parcelid.duplicated().sum()

119

In [13]:
# How many nulls have in each row?
# ...as in... 11995 rows have 33 nulls?
df.isnull().sum(axis =1).value_counts()

33    11995
34    11181
32     8901
31     6004
36     4147
35     3478
29     2531
30     2204
37     1023
28      392
38      227
27      177
44       47
26       30
39       29
40       15
24       12
25       11
43       10
42        7
45        6
41        6
23        2
48        2
46        1
47        1
dtype: int64

### 3. Write a function that takes in a dataframe of observations and attributes and returns a dataframe where each row is an atttribute name, the first column is the number of rows with missing values for that attribute, and the second column is percent of total rows that have missing values for that attribute. Run the function and document takeaways from this on how you want to handle missing values.

In [14]:
def missing_values_col_wise(df):
    '''
    Function that takes in a df and returns a list of attributes with the number and percent
    of missing values for that attribute.
    '''
    new_df = pd.DataFrame(df.isnull().sum())
    new_df['number_missing'] = df.isnull().sum()
    new_df['percent_missing'] = df.isnull().sum()/len(df)*100
    new_df.drop([0], axis=1, inplace=True)
    return new_df

In [15]:
missing_cols = missing_values_col_wise(df)
missing_cols

                              number_missing  percent_missing
typeconstructiontypeid                 52363        99.855070
storytypeid                            52392        99.910372
propertylandusetypeid                      0         0.000000
parcelid                                   0         0.000000
heatingorsystemtypeid                  18504        35.286714
buildingclasstypeid                    52439       100.000000
architecturalstyletypeid               52369        99.866512
airconditioningtypeid                  38801        73.992639
id                                         0         0.000000
basementsqft                           52392        99.910372
bathroomcnt                                0         0.000000
bedroomcnt                                 0         0.000000
buildingqualitytypeid                  18699        35.658575
calculatedbathnbr                        137         0.261256
decktypeid                             52050        99.258186
finishedfloor1squarefeet               48060        91.649345
calculatedfinishedsquarefeet              82         0.156372
finishedsquarefeet12                     247         0.471023
finishedsquarefeet13                   52439       100.000000
finishedsquarefeet15                   52439       100.000000
finishedsquarefeet50                   48060        91.649345
finishedsquarefeet6                    52274        99.685349
fips                                       0         0.000000
fireplacecnt                           45198        86.191575
fullbathcnt                              137         0.261256
garagecarcnt                           34426        65.649612
garagetotalsqft                        34426        65.649612
hashottuborspa                         50924        97.110929
latitude                                   0         0.000000
longitude                                  0         0.000000
lotsizesquarefeet                        369         0.703675
poolcnt                                41343        78.840176
poolsizesum                            51572        98.346650
pooltypeid10                           51995        99.153302
pooltypeid2                            51368        97.957627
pooltypeid7                            42430        80.913061
propertycountylandusecode                  0         0.000000
propertyzoningdesc                     18591        35.452621
rawcensustractandblock                     0         0.000000
regionidcity                            1037         1.977536
regionidcounty                             0         0.000000
regionidneighborhood                   33406        63.704495
regionidzip                               26         0.049581
roomcnt                                    0         0.000000
threequarterbathnbr                    45715        87.177482
unitcnt                                18592        35.454528
yardbuildingsqft17                     50502        96.306184
yardbuildingsqft26                     52376        99.879860
yearbuilt                                116         0.221209
numberofstories                        37880        72.236313
fireplaceflag                          52358        99.845535
structuretaxvaluedollarcnt                84         0.160186
taxvaluedollarcnt                          1         0.001907
assessmentyear                             0         0.000000
landtaxvaluedollarcnt                      1         0.001907
taxamount                                  4         0.007628
taxdelinquencyflag                     50360        96.035394
taxdelinquencyyear                     50360        96.035394
censustractandblock                      123         0.234558
airconditioningdesc                    38801        73.992639
architecturalstyledesc                 52369        99.866512
buildingclassdesc                      52439       100.000000
heatingorsystemdesc                    18504        35.286714
logerror                                   0         0.000000
maxdate                                    0         0.000000
propertylandusedesc                        0         0.000000
storydesc                              52392        99.910372
typeconstructiondesc                   52363        99.855070

In [16]:
missing_cols.index

Index(['typeconstructiontypeid', 'storytypeid', 'propertylandusetypeid',
       'parcelid', 'heatingorsystemtypeid', 'buildingclasstypeid',
       'architecturalstyletypeid', 'airconditioningtypeid', 'id',
       'basementsqft', 'bathroomcnt', 'bedroomcnt', 'buildingqualitytypeid',
       'calculatedbathnbr', 'decktypeid', 'finishedfloor1squarefeet',
       'calculatedfinishedsquarefeet', 'finishedsquarefeet12',
       'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50',
       'finishedsquarefeet6', 'fips', 'fireplacecnt', 'fullbathcnt',
       'garagecarcnt', 'garagetotalsqft', 'hashottuborspa', 'latitude',
       'longitude', 'lotsizesquarefeet', 'poolcnt', 'poolsizesum',
       'pooltypeid10', 'pooltypeid2', 'pooltypeid7',
       'propertycountylandusecode', 'propertyzoningdesc',
       'rawcensustractandblock', 'regionidcity', 'regionidcounty',
       'regionidneighborhood', 'regionidzip', 'roomcnt', 'threequarterbathnbr',
       'unitcnt', 'yardbuildingsqft17', 'yardbuildingsqft26', 'yearbuilt',
       'numberofstories', 'fireplaceflag', 'structuretaxvaluedollarcnt',
       'taxvaluedollarcnt', 'assessmentyear', 'landtaxvaluedollarcnt',
       'taxamount', 'taxdelinquencyflag', 'taxdelinquencyyear',
       'censustractandblock', 'airconditioningdesc', 'architecturalstyledesc',
       'buildingclassdesc', 'heatingorsystemdesc', 'logerror', 'maxdate',
       'propertylandusedesc', 'storydesc', 'typeconstructiondesc'],
      dtype='object')

### Takeaways, missing values: 
Drop all columns over 50% except...
- pool count: i think pool count is 0 unless otherwise specified
- fireplace count: same
-

### 4. Write a function that takes in a dataframe and returns a dataframe with 3 columns: the number of columns missing, percent of columns missing, and number of rows with n columns missing. Run the function and document takeaways from this on how you want to handle missing values.

In [17]:
def missing_values_row_wise(df):
    '''
    Function that takes in a df and returns a list of rows with the number and percent
    of missing values.
    '''
    new_df = pd.DataFrame(df.isnull().sum(axis =1).value_counts())
    new_df['percent_missing'] = new_df.index/len(df.columns)*100
    new_df['num_of_rows'] = df.isnull().sum(axis =1).value_counts()
    new_df.drop([0], axis=1, inplace=True)
    new_df.index.rename('num_cols_missing_from_row', inplace = True)
    return new_df

In [18]:
missing_rows = missing_values_row_wise(df)
missing_rows

                           percent_missing  num_of_rows
num_cols_missing_from_row
33                               48.529412        11995
34                               50.000000        11181
32                               47.058824         8901
31                               45.588235         6004
36                               52.941176         4147
35                               51.470588         3478
29                               42.647059         2531
30                               44.117647         2204
37                               54.411765         1023
28                               41.176471          392
38                               55.882353          227
27                               39.705882          177
44                               64.705882           47
26                               38.235294           30
39                               57.352941           29
40                               58.823529           15
24                               35.294118           12
25                               36.764706           11
43                               63.235294           10
42                               61.764706            7
45                               66.176471            6
41                               60.294118            6
23                               33.823529            2
48                               70.588235            2
46                               67.647059            1
47                               69.117647            1

### Takeaways, missing values row-wise: let's drop everything above fifty percent...actually, first let's drop columns and repeat process.

## Prepare

### 1. Remove any properties that are likely to be something other than single unit properties. (e.g. no duplexes, no land/lot, ...). There are multiple ways to estimate that a property is a single unit, and there is not a single "right" answer. But for this exercise, do not purely filter by unitcnt as we did previously. Add some new logic that will reduce the number of properties that are falsely removed. You might want to use # bedrooms, square feet, unit type or the like to then identify those with unitcnt not defined.

In [19]:
df.unitcnt.value_counts()

1.0    33817
2.0       29
3.0        1
Name: unitcnt, dtype: int64

In [22]:
df.head(1).T

                                                      0
typeconstructiontypeid                              NaN
storytypeid                                         NaN
propertylandusetypeid                             261.0
parcelid                                       14297519
heatingorsystemtypeid                               NaN
buildingclasstypeid                                 NaN
architecturalstyletypeid                            NaN
airconditioningtypeid                               NaN
id                                              1727539
basementsqft                                        NaN
bathroomcnt                                         3.5
bedroomcnt                                          4.0
buildingqualitytypeid                               NaN
calculatedbathnbr                                   3.5
decktypeid                                          NaN
finishedfloor1squarefeet                            NaN
calculatedfinishedsquarefeet                     3100.0
finishedsquarefeet12                             3100.0
finishedsquarefeet13                                NaN
finishedsquarefeet15                                NaN
finishedsquarefeet50                                NaN
finishedsquarefeet6                                 NaN
fips                                             6059.0
fireplacecnt                                        NaN
fullbathcnt                                         3.0
garagecarcnt                                        2.0
garagetotalsqft                                   633.0
hashottuborspa                                      NaN
latitude                                     33634931.0
longitude                                  -117869207.0
lotsizesquarefeet                                4506.0
poolcnt                                             NaN
poolsizesum                                         NaN
pooltypeid10                                        NaN
pooltypeid2                                         NaN
pooltypeid7                                         NaN
propertycountylandusecode                           122
propertyzoningdesc                                  NaN
rawcensustractandblock                  60590630.072012
regionidcity                                    53571.0
regionidcounty                                   1286.0
regionidneighborhood                                NaN
regionidzip                                     96978.0
roomcnt                                             0.0
threequarterbathnbr                                 1.0
unitcnt                                             NaN
yardbuildingsqft17                                  NaN
yardbuildingsqft26                                  NaN
yearbuilt                                        1998.0
numberofstories                                     NaN
fireplaceflag                                       NaN
structuretaxvaluedollarcnt                     485713.0
taxvaluedollarcnt                             1023282.0
assessmentyear                                   2016.0
landtaxvaluedollarcnt                          537569.0
taxamount                                      11013.72
taxdelinquencyflag                                  NaN
taxdelinquencyyear                                  NaN
censustractandblock                    60590630072012.0
airconditioningdesc                                 NaN
architecturalstyledesc                              NaN
buildingclassdesc                                   NaN
heatingorsystemdesc                                 NaN
logerror                                       0.025595
maxdate                                      2017-01-01
propertylandusedesc           Single Family Residential
storydesc                                           NaN
typeconstructiondesc                                NaN

In [23]:
df.maxdate

0        2017-01-01
1        2017-01-01
2        2017-01-01
3        2017-01-01
4        2017-01-01
            ...
52434    2017-09-19
52435    2017-09-20
52436    2017-09-21
52437    2017-09-21
52438    2017-09-25
Name: maxdate, Length: 52439, dtype: object

In [24]:
max(df.maxdate)

'2018-05-25'

In [25]:
df.maxdate.sort_values()

0        2017-01-01
1        2017-01-01
2        2017-01-01
3        2017-01-01
4        2017-01-01
            ...
52435    2017-09-20
52437    2017-09-21
52436    2017-09-21
52438    2017-09-25
10142    2018-05-25
Name: maxdate, Length: 52439, dtype: object